# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-jsp-ecom-platform
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-jsp-ecom-platform
  template:
    metadata:
      labels:
        app: test-jsp-ecom-platform
    spec:
      containers:
      - name: test-jsp-ecom-platform
        image: test-jsp-ecom-platform:slim
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: test-jsp-ecom-platform-service
spec:
  type: LoadBalancer
  selector:
    app: test-jsp-ecom-platform
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8082
