services:
  mysql:
    image: mysql:8.0
    container_name: simplecurd-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Sree@1324
      MYSQL_DATABASE: BankDb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  app:
    build: .
    container_name: simplecurd-app
    ports:
      - "8088:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/BankDb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Sree@1324
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
