apiVersion: v1
kind: Service
metadata:
  name: test-jsp-ecom-platform-service
spec:
  type: LoadBalancer
  selector:
    app: test-jsp-ecom-platform
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8082